FROM golang:1.21-alpine as build
LABEL authors="oliverkirk-sudo"

# RUN apk add --update redis

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o warpgpt

FROM gcr.io/distroless/static-debian11
COPY --from=build /app/warpgpt /app/warpgpt
ENTRYPOINT ["/app/warpgpt"]


# FROM golang:1.21-alpine as build

# WORKDIR /go/src/app
# COPY . .

# RUN go mod download
# RUN go vet -v
# RUN go test -v

# RUN CGO_ENABLED=0 go build -o /go/bin/app

# FROM gcr.io/distroless/static-debian11

# COPY --from=build /go/bin/app /
# CMD ["/app"]