FROM golang:1.21-alpine as build
LABEL authors="oliverkirk-sudo"

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build -o warpgpt

FROM gcr.io/distroless/static-debian11
COPY --from=build /app/warpgpt /app/warpgpt
WORKDIR /app
CMD ["./warpgpt"]