FROM golang:1.21-alpine as build
LABEL authors="oliverkirk-sudo"

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o warpgpt

FROM gcr.io/distroless/static-debian11
COPY --from=build /app/warpgpt /app/warpgpt
CMD ["/app/warpgpt"]